### ISSUE TITLE
generate knock:install fail

### ISSUE THREAD

**Issue by onesup** [nsarno/knock#116]
I use `activeadmin` gem for this project.
I added `knock` gem into my `Gemfile` and I try to `rails generate knock:install` and then it was fail and leave this error logs.

```
/Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/namespace.rb:217:in `eval': Unable to autoload constant Engine, expected /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/knock-2.0/lib/knock/engine.rb to define it (LoadError)
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:203:in `const_missing'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:543:in `load_missing_constant'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:203:in `const_missing'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:270:in `const_get'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:270:in `block in constantize'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `inject'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `constantize'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/inherited_resources-4434f0ae72f7/lib/inherited_resources/class_methods.rb:370:in `block in initialize_resources_class_accessors!'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/inherited_resources-4434f0ae72f7/lib/inherited_resources/class_methods.rb:368:in `delete_if'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/inherited_resources-4434f0ae72f7/lib/inherited_resources/class_methods.rb:368:in `initialize_resources_class_accessors!'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/bundler/gems/inherited_resources-4434f0ae72f7/lib/inherited_resources/class_methods.rb:404:in `inherited'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/resource_controller.rb:38:in `inherited'
	from (eval):1:in `register_resource_controller'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/namespace.rb:217:in `eval'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/namespace.rb:217:in `register_resource_controller'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/namespace.rb:47:in `register'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:158:in `register'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin.rb:75:in `register'
	from /Users/onesup/projects/today-novel/app/admin/banner.rb:1:in `<top (required)>'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:216:in `block in load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/error.rb:41:in `capture'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:216:in `load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `block in load!'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `load!'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:230:in `routes'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activeadmin-1.0.0.pre4/lib/active_admin.rb:79:in `routes'
	from /Users/onesup/projects/today-novel/config/routes.rb:11:in `block in <top (required)>'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/onesup/projects/today-novel/config/routes.rb:1:in `<top (required)>'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `call'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/onesup/projects/today-novel/config/environment.rb:5:in `<top (required)>'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/onesup/.rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

and this one is my `Gemfile`

```ruby
source 'https://rubygems.org'
ruby '2.2.5'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'activeadmin', '~> 1.0.0.pre4'
gem 'inherited_resources', git: 'https://github.com/activeadmin/inherited_resources.git'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bootstrap', '~> 4.0.0.alpha3.1'
gem 'high_voltage'
gem 'mysql2', '~> 0.3.18'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'i18n_generators'
gem 'enumerize'
gem 'acts-as-taggable-on', '~> 4.0'
gem 'carrierwave', '>= 1.0.0.rc', '< 2.0'
gem 'carrierwave-imageoptimizer', git: 'https://github.com/zaiste/carrierwave-imageoptimizer.git'
gem 'mini_magick'
gem 'active_model_serializers'
gem 'axlsx', git: 'https://github.com/randym/axlsx.git'
gem 'rubyXL', '3.3.22'
gem 'knock'

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'byebug', platform: :mri
end
group :production do
  gem 'unicorn'
  gem 'unicorn-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end

```

**Comment by nsarno** [comment]
This looks like an issue with `activeadmin` rather than `knock`. Please open an issue with them. I haven't had time to look into the `activeadmin` code, but it could be an issue similar to this one https://github.com/cerebris/jsonapi-resources/issues/450.

I'll close this for now, but feel free to reopen if it appears that it's actually an issue with knock.
