### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by HLFH** [nsarno/knock#160]
Hi @nsarno,

Just to let you know that Knock is now working and handles correctly the `DocumentNotFound` exception with the following code in `app/controllers/api/v1/user_token_controller.rb`:

```ruby
module Api::V1
  class UserTokenController < Knock::AuthTokenController

    rescue_from Mongoid::Errors::DocumentNotFound, :with => :not_found

    def create 
      ...
    end

    def not_found
      ...
    end
  end
end
```

I don't know if Knock needs some code to associate directly the `DocumentNotFound` exception to `:not_found`.

**Comment by HLFH** [comment]
In `knock.rb`, as said in https://github.com/nsarno/knock/issues/57, I added: 

> self.current_user_from_handle = -> handle { User.find_by! Knock.handle_attr => handle }
self.current_user_from_token = -> claims { User.find claims['sub'] }

then I have the following issue:

> config/initializers/knock.rb:11:in `block in <top (required)>': **undefined method `current_user_from_handle=' for main:Object (NoMethodError)**
        from /home/myuser/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/knock-66b60437a5ac/lib/knock.rb:29:in `setup'

Do you have any idea @nsarno?

**Comment by HLFH** [comment]
@nsarno Can you check knock with mongoid? It does not seem that it works.

I have an error:

> Mongoid::Errors::DocumentNotFound: \nmessage:\n Document not found for class User with attributes {:email=

**Comment by HLFH** [comment]
Solved with custom exception. Knock works with mongoid. 

```
 rescue_from UserNotFound, with: :not_found
```
