### ISSUE TITLE
When I'm using namespace, I got a RoutingError error.

### ISSUE THREAD

**Issue by bianjingbulb** [nsarno/knock#169]
I'm using a namespace like below. When I access `http://localhost:3000/api/v1/user_token`, 
I got a RoutingError error like this. What I doing wrong. 
```
ActionController::RoutingError (uninitialized constant Api::V1::Knock):
  app/controllers/api/v1/user_token_controller.rb:3:in `<module:V1>'
  app/controllers/api/v1/user_token_controller.rb:2:in `<module:Api>'
  app/controllers/api/v1/user_token_controller.rb:1:in `<top (required)>'

```

Here is my code. ⬇︎
**routes.rb**
```ruby
Rails.application.routes.draw do
  namespace :api, format: 'json' do
    namespace :v1, format: 'json' do
      post 'user_token' => 'user_token#create'
    end
  end
end
```
**users_token_controller.rb**
```ruby
module Api
  module V1
    class UserTokenController < Knock::AuthTokenController
    end
  end
end
```

**application_controller.rb**
```ruby
class ApplicationController < ActionController::Base
  include Knock::Authenticable
end
```

**Comment by bianjingbulb** [comment]
It seems like a error about constant.

**Comment by bianjingbulb** [comment]
Resolved. 
http://stackoverflow.com/questions/44082142/routingerror-error-about-knock
