### ISSUE TITLE
Zeitwerk::NameError

### ISSUE THREAD

**Issue by dhyegocalota** [nsarno/knock#252]
# Description
I'm trying to `include Knock::Authenticable` to my `ApplicationController` but I'm getting an error of `Zeitwerk` lib:

![image](https://user-images.githubusercontent.com/5576007/72293098-2e813480-3629-11ea-90fc-a3e59fc90554.png)

## Log
```
Failure/Error: require 'knock/authenticable'

     Zeitwerk::NameError:
       expected file /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/knock-1.5/lib/knock/authenticable.rb to define constant Authenticable, but didn't
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/zeitwerk-2.2.2/lib/zeitwerk/loader/callbacks.rb:17:in `on_file_autoloaded'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:27:in `block in require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `tap'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
     # ./app/controllers/application_controller.rb:1:in `<top (required)>'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:16:in `require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/actiontext-6.0.2.1/lib/action_text/engine.rb:46:in `block (2 levels) in <class:Engine>'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/actiontext-6.0.2.1/lib/action_text/content.rb:132:in `<top (required)>'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/actiontext-6.0.2.1/lib/action_text/engine.rb:42:in `block (2 levels) in <class:Engine>'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/rack-2.0.8/lib/rack/sendfile.rb:111:in `call'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/rack-cors-1.1.0/lib/rack/cors.rb:100:in `call'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./spec/requests/engineer_spec.rb:5:in `block (4 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:9:in `block (3 levels) in <top (required)>'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/database_cleaner-1.7.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/database_cleaner-1.7.0/lib/database_cleaner/base.rb:100:in `cleaning'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/dhyegocalota/.rvm/gems/ruby-2.5.1@gi-api/gems/database_cleaner-1.7.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:8:in `block (2 levels) in <top (required)>'
```

**Comment by nsarno** [comment]
I believe this should get fixed when #248 is merged. Feel free to review it and let me know.
