### ISSUE TITLE
Failing tests / CI build (uninitialized constant Knock::InstallGenerator)

### ISSUE THREAD

**Issue by getaaron** [nsarno/knock#254]
I noticed that the latest commit on `master` is [failing on CI](https://travis-ci.org/nsarno/knock/builds/623799631):

```
$ bundle exec rake
358Coverage report generated for Unit Tests to /home/travis/build/nsarno/knock/coverage. 156 / 296 LOC (52.7%) covered.
359SimpleCov failed with exit 1/home/travis/build/nsarno/knock/test/generators/install_generator_test.rb:5:in `<class:InstallGeneratorTest>': uninitialized constant Knock::InstallGenerator (NameError)
```

I was going to try to fix it and open a PR, but when I run the same command locally I get a different error:

```
Coverage report generated for Unit Tests to /Users/aaron/knock/coverage. 47 / 51 LOC (92.16%) covered.
SimpleCov failed with exit 1Traceback (most recent call last):
	23: from /Library/Ruby/Gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `<main>'
	22: from /Library/Ruby/Gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `select'
	21: from /Library/Ruby/Gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	20: from /Library/Ruby/Gems/2.6.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `require'
	19: from /Users/aaron/knock/test/dummy/test/controllers/admin_protected_controller_test.rb:1:in `<top (required)>'

… snip …

	 1: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/Library/Ruby/Gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
rake aborted!
```

I tried adding a blank manifest file:

```
mkdir -p app/assets/config && echo '{}' > app/assets/config/manifest.js
```

But even after doing that, when running `bundle exec rake` I still get the same `Sprockets::Railtie::ManifestNeededError`.

Still not sure if this is related to the CI failure, but the failing tests & CI make me nervous about using this project in my app.

**Comment by nsarno** [comment]
Thanks for the report. I believe this should get fixed by #248. I'll try to finalise and release it this week if I find the time. Please review and let me know.
