### ISSUE TITLE
Knock not working in production / staging but just fine in develepment env?

### ISSUE THREAD

**Issue by awunder** [nsarno/knock#268]
i have a weird issue.. 

i did override the create method for the usertoken controller to get a bit of a more meaningful response after sign in

```
class UserTokenController < Knock::AuthTokenController
  skip_before_action :verify_authenticity_token, raise: false

  def create
    @message = {}
    @user = @entity
    @user.update_last_signin
    @token = auth_token.token
    @message["msgType"] = "success"
    @message["text"] = "Welcome Back, #{@user.name}!"
    render 'authentication/create'
  end

  private

  def auth_params
    params.require(:auth).permit(:username, :password)
  end
end
```

that works just fine in my dev env.. now i deployed it to the staging env i get an error:

```
I, [2020-07-31T17:33:19.569167 #20740]  INFO -- : [0352752b-71f4-4598-8105-09e919ffd85c] Completed 200 OK in 30ms (Views: 14.8ms | ActiveRecord: 9.4ms | Allocations: 5864)
I, [2020-07-31T17:33:54.229093 #20740]  INFO -- : [addd05ce-ee16-422b-ae48-e2142114df2f] Started POST "/authentication/signin" for 46.124.112.159 at 2020-07-31 17:33:54 +0200
I, [2020-07-31T17:33:54.250915 #20740]  INFO -- : [addd05ce-ee16-422b-ae48-e2142114df2f] Processing by UserTokenController#create as JSON
I, [2020-07-31T17:33:54.251112 #20740]  INFO -- : [addd05ce-ee16-422b-ae48-e2142114df2f]   Parameters: {"auth"=>{"username"=>"andreas", "password"=>"[FILTERED]"}, "user_token"=>{"auth"=>{"username"=>"andreas", "password"=>"[FILTERED]"}}}
D, [2020-07-31T17:33:54.282677 #20740] DEBUG -- : [addd05ce-ee16-422b-ae48-e2142114df2f]   User Load (1.3ms)  SELECT "users".* FROM "users" WHERE "users"."username" = $1 LIMIT $2  [["username", "andreas"], ["LIMIT", 1]]
D, [2020-07-31T17:33:54.601951 #20740] DEBUG -- : [addd05ce-ee16-422b-ae48-e2142114df2f]    (0.5ms)  BEGIN
D, [2020-07-31T17:33:54.603906 #20740] DEBUG -- : [addd05ce-ee16-422b-ae48-e2142114df2f]   User Update (1.2ms)  UPDATE "users" SET "last_signin" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["last_signin", "2020-07-31 15:33:54.595697"], ["updated_at", "2020-07-31 15:33:54.598896"], ["id", 1]]
D, [2020-07-31T17:33:54.606406 #20740] DEBUG -- : [addd05ce-ee16-422b-ae48-e2142114df2f]    (1.4ms)  COMMIT
I, [2020-07-31T17:33:54.608853 #20740]  INFO -- : [addd05ce-ee16-422b-ae48-e2142114df2f] Completed 500 Internal Server Error in 358ms (ActiveRecord: 8.5ms | Allocations: 10011)
F, [2020-07-31T17:33:54.610178 #20740] FATAL -- : [addd05ce-ee16-422b-ae48-e2142114df2f]
[addd05ce-ee16-422b-ae48-e2142114df2f] TypeError (no implicit conversion of nil into String):
[addd05ce-ee16-422b-ae48-e2142114df2f]
[addd05ce-ee16-422b-ae48-e2142114df2f] app/controllers/user_token_controller.rb:8:in `create'
```

so, it does sign me in but auth_token is empty.

so i just tried to remove the create method completely, for testing purposes, if it runs through, but it doesnt. it still fails with an empty token, this time with:

```
I, [2020-07-31T17:33:56.792123 #20773]  INFO -- : [9ce8ef14-7349-4f7f-9e26-67077152f076] Completed 200 OK in 67ms (Views: 24.6ms | ActiveRecord: 17.0ms | Allocations: 8582)
I, [2020-07-31T17:35:00.581457 #23745]  INFO -- : [1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] Started POST "/authentication/signin" for 46.124.112.159 at 2020-07-31 17:35:00 +0200
I, [2020-07-31T17:35:00.588423 #23745]  INFO -- : [1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] Processing by UserTokenController#create as JSON
I, [2020-07-31T17:35:00.588736 #23745]  INFO -- : [1046086e-bdcd-40f3-8bae-8f6f5e4ca55f]   Parameters: {"auth"=>{"username"=>"andreas", "password"=>"[FILTERED]"}, "user_token"=>{"auth"=>{"username"=>"andreas", "password"=>"[FILTERED]"}}}
D, [2020-07-31T17:35:00.639311 #23745] DEBUG -- : [1046086e-bdcd-40f3-8bae-8f6f5e4ca55f]   User Load (1.5ms)  SELECT "users".* FROM "users" WHERE "users"."username" = $1 LIMIT $2  [["username", "andreas"], ["LIMIT", 1]]
I, [2020-07-31T17:35:00.963546 #23745]  INFO -- : [1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] Completed 500 Internal Server Error in 375ms (ActiveRecord: 26.9ms | Allocations: 13267)
F, [2020-07-31T17:35:00.964633 #23745] FATAL -- : [1046086e-bdcd-40f3-8bae-8f6f5e4ca55f]
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] TypeError (no implicit conversion of nil into String):
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f]
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] jwt (1.5.6) lib/jwt.rb:75:in `digest'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] jwt (1.5.6) lib/jwt.rb:75:in `sign_hmac'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] jwt (1.5.6) lib/jwt.rb:36:in `sign'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] jwt (1.5.6) lib/jwt.rb:96:in `encoded_signature'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] jwt (1.5.6) lib/jwt.rb:106:in `encode'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] knock (2.1.1) app/model/knock/auth_token.rb:14:in `initialize'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] knock (2.1.1) app/controllers/knock/auth_token_controller.rb:22:in `new'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] knock (2.1.1) app/controllers/knock/auth_token_controller.rb:22:in `auth_token'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] knock (2.1.1) app/controllers/knock/auth_token_controller.rb:8:in `create'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/abstract_controller/base.rb:195:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/callbacks.rb:135:in `run_callbacks'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `block in instrument'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `instrument'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] rack (2.2.3) lib/rack/etag.rb:27:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] rack (2.2.3) lib/rack/head.rb:12:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
[1046086e-bdcd-40f3-8bae-8f6f5e4ca55f] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

i am still early in development and have a rather short Gemfile:

```
ruby '2.6.6'

gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'jbuilder', '~> 2.7'
gem 'knock'
gem 'bcrypt', '~> 3.1.7'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors'
gem 'rolify'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem "better_errors"
  gem "binding_of_caller"

  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger', '>= 0.1.1'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.3.2)
      actionpack (= 6.0.3.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.3.2)
      actionpack (= 6.0.3.2)
      activejob (= 6.0.3.2)
      activerecord (= 6.0.3.2)
      activestorage (= 6.0.3.2)
      activesupport (= 6.0.3.2)
      mail (>= 2.7.1)
    actionmailer (6.0.3.2)
      actionpack (= 6.0.3.2)
      actionview (= 6.0.3.2)
      activejob (= 6.0.3.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.3.2)
      actionview (= 6.0.3.2)
      activesupport (= 6.0.3.2)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.3.2)
      actionpack (= 6.0.3.2)
      activerecord (= 6.0.3.2)
      activestorage (= 6.0.3.2)
      activesupport (= 6.0.3.2)
      nokogiri (>= 1.8.5)
    actionview (6.0.3.2)
      activesupport (= 6.0.3.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.3.2)
      activesupport (= 6.0.3.2)
      globalid (>= 0.3.6)
    activemodel (6.0.3.2)
      activesupport (= 6.0.3.2)
    activerecord (6.0.3.2)
      activemodel (= 6.0.3.2)
      activesupport (= 6.0.3.2)
    activestorage (6.0.3.2)
      actionpack (= 6.0.3.2)
      activejob (= 6.0.3.2)
      activerecord (= 6.0.3.2)
      marcel (~> 0.3.1)
    activesupport (6.0.3.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    airbrussh (1.4.0)
      sshkit (>= 1.6.1, != 1.7.0)
    bcrypt (3.1.15)
    better_errors (2.7.1)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    bootsnap (1.4.7)
      msgpack (~> 1.0)
    builder (3.2.4)
    byebug (11.1.3)
    capistrano (3.14.1)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (2.0.1)
      capistrano (~> 3.1)
    capistrano-passenger (0.2.0)
      capistrano (~> 3.0)
    capistrano-rails (1.6.1)
      capistrano (~> 3.1)
      capistrano-bundler (>= 1.1, < 3)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    coderay (1.1.3)
    concurrent-ruby (1.1.6)
    crass (1.0.6)
    daemons (1.3.1)
    debug_inspector (0.0.3)
    delayed_job (4.1.8)
      activesupport (>= 3.0, < 6.1)
    delayed_job_active_record (4.1.4)
      activerecord (>= 3.0, < 6.1)
      delayed_job (>= 3.0, < 5)
    erubi (1.9.0)
    ffi (1.13.1)
    ffi (1.13.1-x64-mingw32)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    jbuilder (2.10.0)
      activesupport (>= 5.0.0)
    jwt (1.5.6)
    knock (2.1.1)
      bcrypt (~> 3.1)
      jwt (~> 1.5)
      rails (>= 4.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.6.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (1.0.0)
    mimemagic (0.3.5)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.14.1)
    msgpack (1.3.3)
    msgpack (1.3.3-x64-mingw32)
    net-scp (3.0.0)
      net-ssh (>= 2.6.5, < 7.0.0)
    net-ssh (6.1.0)
    nio4r (2.5.2)
    nokogiri (1.10.10)
      mini_portile2 (~> 2.4.0)
    nokogiri (1.10.10-x64-mingw32)
      mini_portile2 (~> 2.4.0)
    pg (1.2.3)
    pg (1.2.3-x64-mingw32)
    puma (4.3.5)
      nio4r (~> 2.0)
    rack (2.2.3)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.3.2)
      actioncable (= 6.0.3.2)
      actionmailbox (= 6.0.3.2)
      actionmailer (= 6.0.3.2)
      actionpack (= 6.0.3.2)
      actiontext (= 6.0.3.2)
      actionview (= 6.0.3.2)
      activejob (= 6.0.3.2)
      activemodel (= 6.0.3.2)
      activerecord (= 6.0.3.2)
      activestorage (= 6.0.3.2)
      activesupport (= 6.0.3.2)
      bundler (>= 1.3.0)
      railties (= 6.0.3.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (6.0.3.2)
      actionpack (= 6.0.3.2)
      activesupport (= 6.0.3.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rake (13.0.1)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rolify (5.3.0)
    ruby_dep (1.5.0)
    spring (2.1.0)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.21.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (1.0.1)
    thread_safe (0.3.6)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    tzinfo-data (1.2020.1)
      tzinfo (>= 1.0.0)
    websocket-driver (0.7.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    zeitwerk (2.4.0)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  bcrypt (~> 3.1.7)
  better_errors
  binding_of_caller
  bootsnap (>= 1.4.2)
  byebug
  capistrano
  capistrano-bundler
  capistrano-passenger (>= 0.1.1)
  capistrano-rails
  capistrano-rvm
  daemons
  delayed_job_active_record
  jbuilder (~> 2.7)
  knock
  listen (>= 3.0.5, < 3.2)
  pg (>= 0.18, < 2.0)
  puma (~> 4.1)
  rack-cors
  rails (~> 6.0.3, >= 6.0.3.2)
  rolify
  spring
  spring-watcher-listen (~> 2.0.0)
  tzinfo-data

RUBY VERSION
   ruby 2.6.6p146

BUNDLED WITH
   1.17.2
```

i am developing on windows but the staging runs on linux (dont ask...) - idk if it has something to do with it though..

thanks,
Andreas

**Comment by awunder** [comment]
using the master from github fixes the issue.. i hope its fine to use it...
